### ISSUE TITLE
Salvar o estado de publicacao do mock no db apos criacao do dominio

### ISSUE THREAD

**Issue by J0sueTM** [moclojer/moclojer-app#199]
- [x] Salvar estado de publicacao no DB
- [x] Barrar fluxo de criacao de dominio de mock ja publicado
- [x] Atualizar status de publicacao
- [x] Retornar esse dado em request de dados do mock pelo front
