### ISSUE TITLE
atualizar implementacao do componente de mq

### ISSUE THREAD

**Issue by J0sueTM** [moclojer/moclojer-app#318]
- [x] https://github.com/moclojer/clj-rq/issues/4
- [x] https://github.com/moclojer/clj-rq/issues/1
- [x] #333
- [x] https://github.com/moclojer/components/issues/3
- [x] moclojer/clj-rq#11
- [x] #334

precisamos atualizar o pacote `clj-rq` com o que temos/usamos no privado e trocar o privado pelo pacote `clj-rq`
