### ISSUE TITLE
Visão de curto prazo: o que precisamos ter para o lançamento? Ser usuário ativo do moclojer

### ISSUE THREAD

**Issue by avelino** [moclojer/moclojer-app#349]
> precisamos ser usuários da nosso própria solução, assim pegaremos o problema de forma pro ativa e não reativa quando o usuário tiver problema (de forma reativa, agindo quando o usuário reportar problema).

**ref:** https://github.com/moclojer/moclojer/issues/263

Dado a premissa acima pensei em um caso de uso, que não necessariamente precisa do moclojer, mas podemos usar, dado que nosso foco como empresa é contribuir com o ecossistema clojure (desenvolvendo boas soluções foss) podemos desenvolver um _"proxy"_ de webhook do GitHub para Discord como temos no canal `#-github-updates` (lá usamos o webhook do Discord).

Para os projetos fechados (do cloud) a ideia é enviar logs do webhook para o canal fechado `-github-update`.

Provavelmente teremos que implementar recurso na parte de webhook do moclojer foss, onde pegue as variáveis do header recebida no request e repasse para a chamada de webhook feita em background.

a baixo coloco o link para o repositório que estou versionando o mock `yaml` para o Discord

**Como esto local?**

```sh
curl -X POST 127.0.0.1:8000/github/moclojer-app \
	-H "X-GitHub-Delivery: 802fdfc0-237d-11ef-89f8-e09b083ba754" \
    -H "X-GitHub-Event: issue_comment" \
    -H "X-GitHub-Hook-ID: 473302352" \
    -H "X-GitHub-Hook-Installation-Target-ID: 533454006" \
    -H "X-GitHub-Hook-Installation-Target-Type: repository" \
    -H "Content-Type: application/json" \
    -d @../moclojer/payload-github.json
```
subo o yaml abaixo no moclojer local e faço o request (cURL acima) para o moclojer.

**discord notification:**

https://github.com/moclojer/mocks-cloud/blob/6d1053f004d223b2b6deb5f9b6616f58eef85793/discord-moclojer-notification.yml#L1-L36

**github payload:**
https://github.com/moclojer/mocks-cloud/blob/main/payload-github-example.json

> resolvendo esse EPICO acredito que estamos "preparado" para trazer trafego para o site do moclojer e estimular as pessoas usar!

Possivelmente será uma feature que podemos usar como *"marketing"* para atrair usuários para o moclojer.

## todos

* [x] https://github.com/moclojer/moclojer/pull/272
* [x] https://github.com/moclojer/moclojer/pull/269
* [x] https://github.com/moclojer/moclojer/pull/277
* [x] https://github.com/moclojer/moclojer/pull/262
